export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";

export const SET_NEW_ARTICLE_TITLE = "SET_NEW_ARTICLE_TITLE";
export const DELETE_CURRENT_ARTICLE = "DELETE_CURRENT_ARTICLE";
export const RESTORE_CURRENT_ARTICLE = "RESTORE_CURRENT_ARTICLE";

export const OPEN_DIALOG_WINDOW = "OPEN_DIALOG_WINDOW";
export const CLOSE_DIALOG_WINDOW = "CLOSE_DIALOG_WINDOW";
export const AGREE_FOR_RESTORE = "AGREE_FOR_RESTORE";